{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fleet-secret.fullname" . }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
    name: {{ .Values.externalSecret.secretStoreRefName }}
  refreshInterval: "1m"
  target:
    name: {{ include "fleet-secret.fullname" . }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "{{`{{ .metadata }}`}}"
      - target: Annotations
        literal: "aws_central_region: {{ .Values.externalSecret.aws_central_region }}"
      {{- if .Values.externalSecret.annotations }}
      - target: Annotations
        literal: |-
          {{- .Values.externalSecret.annotations  | toYaml | nindent 10  }}
      {{- end }}
      - target: Labels
        literal: "{{`{{ .addons }}`}}"
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: cluster"
      - target: Labels
        literal: "fleet_member: {{ .Values.externalSecret.fleet_member }}"
      - target: Labels
        literal: "cluster_name: '{{`{{ .cluster_name }}`}}'"
      - target: Labels
        literal: "environment: '{{`{{ .environment }}`}}'"
      data:
        config: "{{`{{ .config }}`}}"
        name: "{{`{{ .cluster_name }}`}}"
        server: {{ if ne .Values.externalSecret.server "control-plane" }}"https://kubernetes.default.svc"{{ else }}"{{`{{ .server }}`}}"{{ end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretManagerSecretName }}
{{- end }}